drop database if exists springboot_hibernate;
create database springboot_hibernate;

use springboot_hibernate;





CREATE TABLE PRODUCTO
(
   ID_PRODUCTO BIGINT NOT NULL AUTO_INCREMENT,
   CANTIDAD INTEGER,
   NOMBRE VARCHAR (40) NOT NULL,
   DESCRIPCION VARCHAR (40) NOT NULL,
   PRECIO FLOAT NOT NULL,
   DESCUENTO INT NOT NULL,
   PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE USUARIO
(
   ID_USUARIO BIGINT NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR (40) NOT NULL,
   APELLIDOS VARCHAR (40) NOT NULL,
   USERNAME VARCHAR (40) NOT NULL,
   CONTRASEÑA VARCHAR (120) NOT NULL,
   EMAIL VARCHAR (40) NOT NULL,
   FECHA_NAC VARCHAR (40) NOT NULL,
   NUMERO_TARJETA INT NOT NULL,
   CODIGO_SEGURIDAD INT NOT NULL,
   DIRECCION_FACTURACION VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE ROL
(
   ID_ROL BIGINT AUTO_INCREMENT,
   NOMBRE_ROL VARCHAR (40) NOT NULL,
   PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO_ROL
(
   ID_USUARIO BIGINT NOT NULL,
   ID_ROL BIGINT ,
      PRIMARY KEY
   (
      ID_USUARIO,
      ID_ROL
   ),
   CONSTRAINT FK_USUARIO_ROL_1 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ON DELETE CASCADE,
   CONSTRAINT FK_USUARIO_ROL_2 FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE COMPRA(

	ID_COMPRA BIGINT NOT NULL AUTO_INCREMENT,
	PRECIO BIGINT,
	PRIMARY KEY (ID_COMPRA),
	ID_USUARIO BIGINT NOT NULL,
	CONSTRAINT FK_COMPRA_USUARIO
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
	
	
);

  CREATE TABLE PRODUCTO_COMPRA (
       ID_COMPRA BIGINT NOT  NULL,
        ID_PRODUCTO BIGINT NOT NULL,
        PRIMARY KEY (ID_COMPRA, ID_PRODUCTO),
        CONSTRAINT FK_COMPRA_PRODUCTO_1
        FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA) 
		ON DELETE CASCADE,
        CONSTRAINT FK_COMPRA_PRODUCTO_2
        FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
        ON DELETE CASCADE
		
    ) ;


	 


     CREATE TABLE PREGUNTA (
	ID_PREGUNTA BIGINT NOT NULL AUTO_INCREMENT,
        TEXTO VARCHAR (500) NOT NULL,
        FECHA DATE NOT NULL,
        ID_USUARIO BIGINT NOT NULL,
	ID_PRODUCTO BIGINT NOT NULL,
        PRIMARY KEY (ID_PREGUNTA),
        CONSTRAINT FK_PREGUNTA_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
	CONSTRAINT FK_PREGUNTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
	     	
);



 

CREATE TABLE RESPUESTA(

	ID_RESPUESTA BIGINT NOT NULL AUTO_INCREMENT,
	TEXTO VARCHAR(500) NOT NULL,
	FECHA DATE NOT NULL,
	ID_USUARIO BIGINT NOT NULL,
	ID_PREGUNTA BIGINT NOT NULL,
	PRIMARY KEY (ID_RESPUESTA),
	CONSTRAINT FK_RESPUESTA_USUARIO
	FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
	CONSTRAINT FK_RESPUESTA_PREGUNTA
	FOREIGN KEY(ID_PREGUNTA) REFERENCES PREGUNTA(ID_PREGUNTA)
	
);


CREATE TABLE IMAGEN
(
   ID_IMAGEN BIGINT NOT NULL AUTO_INCREMENT,
   NOMBRE VARCHAR (40) NOT NULL,
   IMAGEN LONGBLOB NOT NULL,
   ID_PRODUCTO BIGINT NOT NULL,
   PRIMARY KEY (ID_IMAGEN),
   CONSTRAINT FK_IMAGEN_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON UPDATE CASCADE 
   
);


